### ISSUE TITLE
Deploy new Semaphore contracts on Arbitrum

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#229]
**Tasks**:

- [x] Further tests on Goerli contracts
- [x] Deploy contracts
- [x] Create new subgraph
- [x] Add addresses on doc v3
- [x] Update `@semaphore-protocol/subgraph` lib
