### ISSUE TITLE
Make steps to generate and verify Semaphore proofs easier

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#230]
**Description**:

Proofs can be generated with the `@semaphore-protocol/proof` library and verified with both the library itself and the contracts. However, the values that the function `generateProof` returns can be confusing. For example, the signal and the external nullifier in the `publicSignals` object are hashed and thus different from the original values, which should be used to verify on-chain proofs. Also, the `packToSolidityProof` function can be omitted and the proof can directly be formatted to be compatible with both the on-chain and off-chain verifier functions.

**Tasks**:

- [x] Update `@semaphore-protocol/proof` lib (src/test/readme)
- [x] Update code that depends on `@semaphore-protocol/proof` (contracts/cli/boilerplate/)
- [x] Update docs (guides-proofs/landing-page)
