### ISSUE TITLE
Deploy new Semaphore contracts on Polygon testnet

### ISSUE THREAD

**Issue by andyguzmaneth** [semaphore-protocol/semaphore#233]
**Tasks**:

 - [x] Deploy contracts on Mumbai
 - [x] Create new subgraph
 - [x] Update `@semaphore-protocol/data` lib
 - [x] Add addresses on doc v3
