### ISSUE TITLE
Deploy new Semaphore contracts on Optimism testnet

### ISSUE THREAD

**Issue by andyguzmaneth** [semaphore-protocol/semaphore#234]
**Tasks**:

 - [x] Deploy contracts on Optimism Goerli
 - [x] Create new subgraph
 - [x] Add addresses on doc v3
 - [x] Update `@semaphore-protocol/data` lib
