### ISSUE TITLE
Create lib for getting contract logs with `ethers`

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#256]
**Tasks**:

- [x] Create new package
- [x] Copy code from `@semaphore-protocol/subgraph` to `@semaphore-protocol/data`
- [x] Create new `SemaphoreEthers` class
- [x] Mock tests
- [x] Update README file and include `SemaphoreEthers` functions
