### ISSUE TITLE
Deploy new Semaphore contracts on Arbitrum testnet

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#275]
**Tasks**:

- [x] Deploy contracts on Arbitrum Goerli
- [x] Create new subgraph
- [x] Add addresses on doc v3
- [x] Update `@semaphore-protocol/data` lib
