### ISSUE TITLE
The order of the `ProofVerified` event parameters is wrong

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#297]
**Tasks**:

- [x] Fix the bug
- [x] Re-deploy Semaphore to all supported networks
- [x] Verify contracts on Etherscan
- [x] Update contract addresses in our docs
- [x] Re-deploy Semaphore subgraph with new version
- [x] Update `@semaphore-protocol/data` URLs and addresses
