### ISSUE TITLE
Update Semaphore subdomains

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#381]
**Tasks:**

- [x] Move the current Semaphore documentation [website](https://github.com/semaphore-protocol/website) to the main repo (to `apps/docs`)
- [x] #493 
   - [x] Add link to Semaphore X inside the documentation 
   - [x] Remove old landing page from the documentation 
   - [x] #426 
- [x] Create `docs` subdomain (CNAME on Cloudflare) 
- [x] Create a new AWS Amplify app for docs.semaphore.pse.dev
- [x] Connect the main domain to the new website (currently on [website.semaphore.pse.dev](https://website.semaphore.pse.dev) for testing)
- [x] Archive website repo
