### ISSUE TITLE
Adapt website to mobile screens (responsive)

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#392]
**Tasks**:

Pages:
- [x] Home page
- [x] Build page
  - [x] Check Tools Cards in small screens (phone) 
- [x] Projects page
- [x] Learn page
  - [x] Align content with the container (videos and articles)
  - [x] Tabs should scroll horizontally in phone screens
  - [x] Code block should cover the entire screen width in tablet and phone

Components:
- [x] Navbar
- [x] Footer
- [x] Other components

___

- [x] Final review
