### ISSUE TITLE
Add documentation for V4.0.0-alpha

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#479]
**Tasks**:

- [x] Add a new version
- [x] Update content
- [x] Show versions in the navbar
- [x] Add announcement for V4-alpha
