### ISSUE TITLE
Create fake zk artifacts for all tree depths (from 1 to 12)

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#482]
**Tasks**:

- [x] Upload `zkey`/`wasm` files to Cloudflare
- [x] Add verification keys to the `@semaphore-protocol/proof` library
- [x] Add verification keys to the verifier contract
