### ISSUE TITLE
Add more detailed documentation to Semaphore V4 contracts and libraries

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#483]
**Tasks**:

- [x] Circuits 
- [x] `@semaphore-protocol/contracts`
- [x] Core packages
    - [x] `@semaphore-protocol/identity`
    - [x] `@semaphore-protocol/group`
    - [x] `@semaphore-protocol/proof`
- [x] `@semaphore-protocol/utils`
- [x] `@semphore-protocol/data` https://github.com/semaphore-protocol/semaphore/pull/768
- [x] `@semaphore-protocol/hardhat` https://github.com/semaphore-protocol/semaphore/pull/772
- [x] `@semaphore-protocol/cli` https://github.com/semaphore-protocol/semaphore/pull/771
