### ISSUE TITLE
Fix minor UI issues in the new documentation website

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#525]
**Tasks**:

- [x] Update search bar domain
- [x] Increase logo size in the navbar
- [x] Remove weird lines under the links
- [x] Update link colors
- [x] Set right favicon based on theme
