### ISSUE TITLE
Deploy apps on Vercel

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#645]
**Tasks**:

- [x] Documentation (remove from AWS)
- [x] Website (remove from AWS)
- [x] Benchmarks (remove workflow)
- [x] Explorer (remove previous Vercel project)
- [x] Boilerplate (remove workflow)
    - [x] Remove `dynamic = "force-static"` export from routes
    - [x] Remove `output: "export"` option from NextJS config files
