### ISSUE TITLE
Update Semaphore V4 documentation for V4-beta release

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/semaphore#654]
**Tasks**:

- [x] `quick-setup` will be `getting-started`
- [x] `V4-alpha/doc-link` will be `/doc-link`
- [x] `feat/semaphore-v4` Semaphore Github branch will be `main`
- [x] `version/4` Boilerplate Github branch will be `main`
