### ISSUE TITLE
Update zk-kit dependencies

### ISSUE THREAD

**Issue by vplasencia** [semaphore-protocol/semaphore#776]
**Tasks**:

- [x] `@zk-kit/binary-merkle-root.circom`
- [x] `@zk-kit/imt`
- [x] `@zk-kit/imt.sol`
- [x] `@zk-kit/eddsa-poseidon`
- [x] `@zk-kit/utils`
- [x] `@zk-kit/baby-jubjub`
